Vagrant.configure("2")do|config|
  config.vm.box="centos/7"
  config.vm.network "private_network", ip: "192.168.2.41"
  config.vm.hostname = "tp4.b2"

  config.vbguest.auto_update = false
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", path: "scripts/script_install.sh"

config.vm.define :tp4 do |t|
end

config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.name = "tp4.b2"
end

end