Vagrant.configure("2") do |config|
  config.vm.box = "b2-tp2-centos"

 
  config.vbguest.auto_update = false
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Config une première VM "node1"
  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "192.168.2.21"
    node1.vm.hostname = "node1.tp2.b2"
  
    node1.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = "node1.tp2.b2"

      disk = './disk2.vdi'
      unless File.exist?(disk)
        v.customize ['createhd', '--filename', disk, '--variant', 'Fixed', '--size', 5 * 1024]
      end
        v.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
    end

    # Nginx conf
    node1.vm.provision "file",
      source: "conf/nginx.conf", 
      destination: "/tmp/nginx.conf"
    node1.vm.provision "shell", inline: "cp /tmp/nginx.conf /etc/nginx/nginx.conf"

 
    node1.vm.provision "file", 
      source: "ssl/server.crt", 
      destination: "/tmp/ssl/server.crt"
    node1.vm.provision "file", 
      source: "ssl/server.key", 
      destination: "/tmp/ssl/server.key"
    node1.vm.provision "shell", inline: "cp /tmp/ssl/server.key /etc/pki/tls/private/server.key"
    node1.vm.provision "shell", inline: "cp /tmp/ssl/server.crt /etc/pki/tls/certs/server.crt"

    # Backup
    node1.vm.provision "file", 
      source: "backup.sh", 
      destination: "/tmp/backup.sh"

    node1.vm.provision "shell", path: "conf/node1_conf.sh"

  end

  # Config une deuxième VM "node2"
  config.vm.define "node2" do |node2|
    node2.vm.network "private_network", ip: "192.168.2.22"
    node2.vm.hostname = "node2.tp2.b2"

    node2.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.name = "node2.tp2.b2"
    end

  
    node2.vm.provision "file", 
      source: "ssl/server.crt", 
      destination: "/tmp/ssl/server.crt"

    node2.vm.provision "shell", path: "conf/node2_conf.sh"

  end
end