Vagrant.configure("2") do |config|
  config.vm.box = "b2-tp4-centos"
  
  config.vbguest.auto_update = false
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Gitea node1
  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "192.168.2.41"
    node1.vm.hostname = "node1.tp4.b2"
  
    node1.vm.provider "virtualbox" do |v|
      v.memory = 720
      v.name = "node1.tp4.b2"

      node1.vm.provision "shell", path: "scripts/node1_conf.sh"

      node1.vm.provision "file",
      source: "scripts/conf_gitea/gitea.service", 
      destination: "/tmp/gitea.service"
      node1.vm.provision "shell", inline: "cp /tmp/gitea.service /etc/systemd/system/gitea.service"

      node1.vm.provision "shell", path: "scripts/conf_gitea/setup_gitea.sh"

    end
    
  end

  # MariaDB node2
  config.vm.define "node2" do |node2|
    node2.vm.network "private_network", ip: "192.168.2.42"
    node2.vm.hostname = "node2.tp4.b2"
  
    node2.vm.provider "virtualbox" do |v|
      v.memory = 720
      v.name = "node2.tp4.b2"

      node2.vm.provision "shell", path: "scripts/node2_conf.sh"

    end

  end

  # NGINX node3
  config.vm.define "node3" do |node3|
    node3.vm.network "private_network", ip: "192.168.2.43"
    node3.vm.hostname = "node3.tp4.b2"
    
    node3.vm.provider "virtualbox" do |v|
      v.memory = 720
      v.name = "node3.tp4.b2"

      node3.vm.provision "shell", path: "scripts/node3_conf.sh"

      node3.vm.provision "file",
      source: "conf_nginx/nginx.conf", 
      destination: "/tmp/nginx.conf"
      node3.vm.provision "shell", inline: "cp /tmp/nginx.conf /etc/nginx/nginx.conf"

    end

  end

  # Serv NFS node4
  config.vm.define "node4" do |node4|
    node4.vm.network "private_network", ip: "192.168.2.44"
    node4.vm.hostname = "node4.tp4.b2"
  
    node4.vm.provider "virtualbox" do |v|
      v.memory = 720
      v.name = "node4.tp4.b2"
  
    end
  end
end